# Generated by Django 4.2.4 on 2023-08-22 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storage_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=storage_app.models.csv_file_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV_file',
                'verbose_name_plural': 'CSV_files',
                'ordering': ['pk'],
            },
        ),
    ]
